### ISSUE TITLE
ConcurrentModificationException in QuickFixJSessionHealthIndicator

### ISSUE THREAD

**Issue by dafriz** [esanchezros/quickfixj-spring-boot-starter#111]
When starting up a multiple FIX session service we get ConcurrentModificationExceptions logged, stack trace below

SB: 2.7.14
QF-SBS: 2.15.4

```
java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
at io.allune.quickfixj.spring.boot.actuate.health.QuickFixJSessionHealthIndicator.lambda$doHealthCheck$1(QuickFixJSessionHealthIndicator.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
at io.allune.quickfixj.spring.boot.actuate.health.QuickFixJSessionHealthIndicator.doHealthCheck(QuickFixJSessionHealthIndicator.java:53)
at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
```

Should sessionScheduleMap be changed to a ConcurrentHashMap?

**Comment by esanchezros** [comment]
Hey @dafriz, thanks for reporting this issue. In this case it seems like the `sessionID` could not be found on the session schedule factory and a null `sessionSchedule` was used to modify the map producing the `ConcurrentModificationException`. I will try to make the change but if you want to send a PR it will be much appreciated.
Thanks

**Comment by esanchezros** [comment]
I've fixed this issue, will try to release a new version this week.
Thanks for reporting @dafriz
